name: cleanup-workflow

on:
  workflow_run:
    workflows:
      - "build"
    types: ["requested"]

jobs:
  cancel-duplicated-workflow:
    name: "Cancel duplicated workflow"
    runs-on: ubuntu-latest
    steps:
      - uses: potiuk/cancel-workflow-runs@953e057dc81d3458935a18d1184c386b0f6b5738 # tested
        name: "Cancel duplicate workflows"
        with:
          cancelMode: allDuplicates
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
          skipEventTypes: '["schedule"]'
