name: deploy

on:
  # master only tests
  push:
    branches:
      - master

jobs:
  # caching of these jobs:
  #   - docker-py3-pip- (shared)
  #   - ubuntu py36 37 38-pip-
  #   - os-latest-pip (shared)
  coverage-py3:
    if: github.repository == 'Project-MONAI/MONAI'
    container:
      image: nvcr.io/nvidia/pytorch:20.03-py3  # CUDA 10.2
      options: --gpus all
    runs-on: [self-hosted, linux, x64, common]
    steps:
    - uses: actions/checkout@v2
    - name: cache weekly timestamp
      id: pip-cache
      run: |
        echo "::set-output name=datew::$(date '+%Y-%V')"
    - name: cache for pip
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cache/pip
          ~/.cache/torch
        key: docker-py3-pip-${{ steps.pip-cache.outputs.datew }}
    - name: Install the dependencies
      run: |
        which python
        python -m pip install --upgrade pip wheel
        python -m pip uninstall -y torch torchvision
        python -m pip install torch==1.7.1 torchvision==0.8.2
        python -m pip install -r requirements-dev.txt
    - name: Run unit tests report coverage
      run: |
        python -m pip list
        export LAUNCH_DELAY=$[ $RANDOM % 16 * 60 ]
        echo "Sleep $LAUNCH_DELAY"
        sleep $LAUNCH_DELAY
        nvidia-smi
        export CUDA_VISIBLE_DEVICES=$(python -m tests.utils)
        echo $CUDA_VISIBLE_DEVICES
        stop_time=$((LAUNCH_DELAY + $(date +%s)))
        while [ $(date +%s) -lt $stop_time ]; do
          python -c 'import torch; torch.rand(5, 3, device=torch.device("cuda:0"))';
        done
        python -c "import torch; print(torch.__version__); print('{} of GPUs available'.format(torch.cuda.device_count()))"
        python -c 'import torch; print(torch.rand(5, 3, device=torch.device("cuda:0")))'
        BUILD_MONAI=1 ./runtests.sh --coverage --unittests  # unit tests with coverage report
        export CUDA_VISIBLE_DEVICES=$(python -m tests.utils)
        echo $CUDA_VISIBLE_DEVICES
        BUILD_MONAI=1 ./runtests.sh --coverage --net  # integration tests with coverage report
        coverage xml
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false
        file: ./coverage.xml

  test-py3x:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: cache weekly timestamp
      id: pip-cache
      run: |
        echo "::set-output name=datew::$(date '+%Y-%V')"
    - name: cache for pip
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cache/pip
          ~/.cache/torch
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ steps.pip-cache.outputs.datew }}
    - name: Install the dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install torch==1.7.1 torchvision==0.8.2
        python -m pip install -r requirements-dev.txt
    - name: Run quick tests CPU ubuntu
      run: |
        python -m pip list
        python -c 'import torch; print(torch.__version__); print(torch.rand(5,3))'
        BUILD_MONAI=1 ./runtests.sh --quick --unittests
        coverage xml
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false
        file: ./coverage.xml

  install:  # pip install from github url
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: cache weekly timestamp
      id: pip-cache
      run: |
        echo "::set-output name=datew::$(date '+%Y-%V')"
    - name: cache for pip
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cache/pip
          ~/.cache/torch
        key: ${{ runner.os }}-pip-${{ steps.pip-cache.outputs.datew }}
    - name: Install the default branch no build
      run: |
        BUILD_MONAI=0 pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI
        python -c 'import monai; monai.config.print_config()'
        cd $(python -c 'import monai; import os; print(os.path.dirname(monai.__file__))')
        ls .
        pip uninstall -y monai
    - name: Install the default branch with build
      run: |
        BUILD_MONAI=1 pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI
        python -c 'import monai; monai.config.print_config()'
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Quick test installed
      run: |
        cd $GITHUB_WORKSPACE
        rm -rf monai/
        ls -al .
        python -m pip install -r requirements-min.txt
        python -m tests.min_tests
      env:
        QUICKTEST: True

  local_docker:
    if: github.repository == 'Project-MONAI/MONAI'
    runs-on: [self-hosted, linux, x64, build_only]
    # we only push built container if it is built from master branch
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: docker_build
      run: |
        # build and run original docker image for local registry
        docker build -t localhost:5000/local_monai:latest -f Dockerfile .
        docker push localhost:5000/local_monai:latest
        # build once more w/ tag "latest": remove flake package as it is not needed on hub.docker.com
        sed -i '/flake/d' requirements-dev.txt
        docker build -t projectmonai/monai:latest -f Dockerfile .
        # also push as tag "dockerhub" to local registry
        docker image tag projectmonai/monai:latest localhost:5000/local_monai:dockerhub
        docker push localhost:5000/local_monai:dockerhub
        # distribute as always w/ tag "latest" to hub.docker.com
        echo "${{ secrets.DOCKER_PW }}" | docker login -u projectmonai --password-stdin
        docker push projectmonai/monai:latest
        docker logout

  docker:
    if: github.repository == 'Project-MONAI/MONAI'
    needs: local_docker
    container:
      image: localhost:5000/local_monai:latest
    runs-on: [self-hosted, linux, x64, common]
    steps:
    - name: Import
      run: |
        python -c 'import monai; monai.config.print_config()'
        cd /opt/monai
        ls -al
        ngc --version
        python -m tests.min_tests
      env:
        QUICKTEST: True
