import argparse

def parse_arguments(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument('--message', '--msg', type=str, default=None)
    parser.add_argument('--dataset', type=str, default='real')
    parser.add_argument('--train_path', type=str, default="path_")
    parser.add_argument('--test_path', type=str, default="path_")
    parser.add_argument('--random_seed', type=int, default=100)

    parser.add_argument('--start_epoch', type=int, default = 0)
    parser.add_argument('--start_iter', type=int, default=0)
    parser.add_argument('--epochs', type=int, default=50, help="number of epochs")
    parser.add_argument('--gpu_idx', type=str, default='0')
    parser.add_argument('--lr', type=float, default=0.001)
    parser.add_argument('--batch_size', type=int, default=10)
    parser.add_argument('--lr_decay_epochs', type=str, default='3,5,7', help='where to decay lr, can be a list')
    parser.add_argument('--lr_decay_rate', type=float, default=0.1, help='decay rate for learning rate')
    parser.add_argument('--w', type=int, default=16)
    parser.add_argument('--log_dir', type=str, default="runs")
    parser.add_argument('--checkpoint_dir', type=str, default="checkpoints")
    parser.add_argument('--print_freq', type=int, default=300)
    parser.add_argument('--backbone', type=str, default="CMT_Ti")
    parser.add_argument('--fov', type=str, default=None)
    parser.add_argument('--margin', type=str, default=None)
    parser.add_argument('--resume', action='store_true')
    parser.add_argument('--aug', type=str, default='False'))
    parser.add_argument('--hist_equal', type=str, default="False")
    parser.add_argument('--disease_off', type=str, default=None)
    parser.add_argument('--only_change', type=str, default=None)
    parser.add_argument('--pretrained', type=str, default=None)
    parser.add_argument('--std', type=float, default=0.4)
    parser.add_argument('--mean', type=float, default=0.2)
    parser.add_argument('--change_weight', type=float, default=1.)
    parser.add_argument('--matching_weight', type=float, default=0.01)
    parser.add_argument('--disease_weight', type=float, default=0.5)
    parser.add_argument('--weight-decay', type = float, default = 1e-5, metavar = 'WD',
                help = 'Weight decay (default: 1e-5)')
    
    return parser.parse_args()
